### ISSUE TITLE
Function <SNR>92_restore_cpoptions already exists

### ISSUE THREAD

**Issue by frace** [amdt/sunset#12]
After reloading the plugin a function gets loaded multiple times:

```
Error detected while processing ~/.vim/plugged/sunset/plugin/sunset.vim:
line   21:
E122: Function <SNR>92_restore_cpoptions already exists, add ! to replace it
```
Should be easy to fix, I'd like to send a PR, but don't have enought time right now unfortunately.

**Comment by amdt** [comment]
Thanks for reporting this issue!
