### ISSUE TITLE
Callback functions should start with a capital letter or s:function_name()

### ISSUE THREAD

**Issue by frace** [amdt/sunset#9]
Hello,

first of all thank you for your plugin - it fits perfectly in my setup where I already use f.lux/redshift.
I tried to apply the provided callback functions in order to use different colorschemes at day and night like referenced in `:help sunset`:

```
    function! g:sunset_daytime_callback()
        colorscheme 'Hemisu'
    endfunction

    function! g:sunset_nighttime_callback()
        colorscheme 'Solarized'
    endfunction
```

There are some issues with the example.
First of all the colorscheme declaration does not work because the colorscheme names are quoted. Quotes are not needed in that case.

Next vim complains about the function declarations. The function names need to start with a capital letter or with `s:` instead of `g:`.

It would be nice if you could fix that in order to get colorschemes switched automatically. ;)

Cheers

**Comment by amdt** [comment]
Thanks for using Sunset, I’m glad to hear it’s useful to you.

Thanks also to @jrapakko for the pull request that got the ball rolling on this fix.

**Comment by frace** [comment]
@amdt Thanks a lot for fixing this issue.
